### ISSUE TITLE
How do you deal with identity types that have no validation rules? 

### ISSUE THREAD

**Issue by danielo515** [ostera/reason-design-patterns#13]
Very nice collection of patterns you have here, thanks for sharing. I have been using some of them for some time now and I just discovered your Repository, which is a very nice resource. However there is a little edge case that I didn't find a good way to handle and I didn't saw any way in any of your articles in this repository either. It has to do with types that doesn't have any particular validation rules other than being from a trusted source. My main use case are IDs, to avoid mixing IDs from one entity with IDs of other entities. This IDs doesn't have anything in special, they are all uuids and the only way to know they are correct is by reading them from the DB or doing a round trip to the Db. This all works fine when you are in the core of your app and you just parse the data from the database, however things get tricky when you need to take those IDs from other sources. For example, an incoming Rest request, a CLI input etc. One solution that comes to my mind is to create special serialization formats for those IDs and force clients to use them as I return them, but this may only work for clients that I directly control, and it's probably not going to be very nice to deal with.
How do you approach such scenarios?
Regards

**Comment by leostera** [comment]
I'd have to see your use-case in more detail, but If your IDs require more semantic information, consider using URIs instead.

Instead of `787f1675-2e43-4bfe-a0c0-22016bfcde69`,  try `myapp:resource:company:787f1675-2e43-4bfe-a0c0-22016bfcde69`.

Then you can build a function that parses these URIs into specific IDs for some set of data.

**Comment by danielo515** [comment]
Thanks for your answer @ostera , that is what I tried to express with my poorly worded sentence:

> One solution that comes to my mind is to create special serialization formats for those IDs and force clients to use them as I return them, 

If you are interested in a discussion around this topic, I asked it also in the Ocaml discourse:

https://discuss.ocaml.org/t/how-to-enforce-valid-db-ids-with-phantom-types/10705
