### ISSUE TITLE
Pretty Printing Values link is broken

### ISSUE THREAD

**Issue by nikgraf** [ostera/reason-design-patterns#3]
This line here https://github.com/ostera/reason-design-patterns/blame/master/README.md#L24

**Comment by leostera** [comment]
Sorry @nikgraf, I accidentally published the wrong top-level README! 🙈 It's fixed now in https://github.com/ostera/reason-design-patterns/commit/40453b84bd66d0128f7a7b8902fc603e3ad9bd69
